spring.application.name=CricketBot

spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_URL}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl=update

spring.ai.openai.api-key=${AI_API}
spring.ai.openai.base-url=${AI_URL}
spring.ai.openai.chat.options.model=${AI_MODEL}

jwt.secret= ${JWT_SECRET}
admin.name= ${ADMIN_NAME}
admin.email=${ADMIN_EMAIL}
admin.password= ${ADMIN_PASSWORD}