spring.application.name=CricketBot

spring.datasource.url=${DB_URL:jdbc:h2:mem:testDb}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.ai.openai.api-key=${AI_API}
spring.ai.openai.base-url=${AI_URL}
spring.ai.openai.chat.options.model=${AI_MODEL}

jwt.secret=${JWT_SECRET}
admin.name=${ADMIN_NAME:Admin}
admin.email=${ADMIN_EMAIL:admin@gmail.com}
admin.password=${ADMIN_PASSWORD:admin@123}